### ISSUE TITLE
Add a Section Introducing the Requests and BeautifulSoup Packages

### ISSUE THREAD

**Issue by runderwood** [data-lessons/library-webscraping-DEPRECATED#11]
Provide an introductory example, aligned with the exercises in the browser console, that fetches a document from a given url and scrapes data from its markup using Python `requests` and `BeautifulSoup`.

**Comment by vphill** [comment]
A little more context on this ticket.  

This ticket will build off of the basic structure from a perviously created scraping tutorial from the University of Oklahoma - http://ouinformatics.github.io/swc_beautiful_soup/ 

Instead of the supplied URLs we will use the United Nations Security Council Resolutions found here - http://www.un.org/en/sc/documents/resolutions/

Here is the basic idea for the lesson:

- Load the page with Requests and BeautifulSoup
- Extract the links from the page
- Limit the links to just the years of resolutions
- Output the links to the page that lists resolutions by year
- Load one year and display page contents 

The next section in the lesson will dive deeper into using Python and BeautifulSoup as well as diving a little further into the data on the site.

**Comment by jnothman** [comment]
It turns out the UNSC resolutions dataset that was suggested as a scraping target is very quirky in terms of variation from year to year. See https://github.com/ctds-usyd/library-webscraping/pull/2 where I've built scrapers for it in multiple frameworks
